
spring.application.name=streams

spring.datasource.url=jdbc:mysql://localhost:3306/tareasdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pamela1311
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=false

# Connection pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Logging
logging.level.root=WARN
logging.level.com.laboratorio.streams=INFO
